# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aresta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_a', models.IntegerField()),
                ('sensor_b', models.IntegerField()),
                ('distancia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Deteccao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('pinoFisico', models.IntegerField()),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=130)),
                ('dataHora', models.DateTimeField()),
                ('voltas_realizadas', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('tempo', models.FloatField()),
                ('qtdVoltas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Volta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tempoTotal', models.FloatField()),
                ('velocidadeMedia', models.FloatField()),
                ('velocidadeGeral', models.FloatField()),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedapp.Teste')),
            ],
        ),
        migrations.AddField(
            model_name='deteccao',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedapp.Sensor'),
        ),
        migrations.AddField(
            model_name='deteccao',
            name='volta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedapp.Volta'),
        ),
        migrations.AddField(
            model_name='aresta',
            name='teste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedapp.Teste'),
        ),
    ]
