# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='dataHora',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='descricao',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='qtdVoltas',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='temperatura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='umidade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='voltas_realizadas',
            field=models.IntegerField(null=True),
        ),
    ]
