# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0002_auto_20160424_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aresta',
            name='sensor_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_a', to='speedapp.Sensor'),
        ),
        migrations.AlterField(
            model_name='aresta',
            name='sensor_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_b', to='speedapp.Sensor'),
        ),
    ]
