# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0003_auto_20160424_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='dataUltimoReconhecimento',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 23, 9, 33, 868801, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
