# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0004_sensor_dataultimoreconhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='volta',
            name='tempoCorrente',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volta',
            name='tempoInicial',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
