# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0007_teste_testefinalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='status',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
