# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0011_auto_20160605_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='origem',
            field=models.CharField(choices=[('0', 'modelo'), ('1', 'aplicacao')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
