# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0013_teste_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='dataHoraExecucao',
            field=models.DateTimeField(null=True),
        ),
    ]
