# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0014_teste_datahoraexecucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='tempoTotalMax',
            field=models.FloatField(null=True),
        ),
    ]
