# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0016_auto_20160618_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bpm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField()),
                ('tempo', models.FloatField()),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedapp.Teste')),
            ],
        ),
    ]
