# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0017_bpm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volta',
            old_name='tempoCorrente',
            new_name='tempoFinal',
        ),
    ]
