# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0018_auto_20160815_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='aresta',
            name='descricao',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
